name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.23.8'
        - '1.24.2'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: >-
          WORKAROUND: Fetch tags that points to the revisions
          checked-out(actions/checkout#1467)
        run: |-
          git fetch --tags --force

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make cross
      - name: Upload macadam artifact
        if: matrix.go == '1.23.8'
        uses: actions/upload-artifact@v4
        with:
          name: macadam binaries
          path: "./bin/*"


  test:
    needs: build
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-13
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
      - name: Test
        run: make test


  lint:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
      - name: Run 'make check'
        run: make check
